### ISSUE TITLE
Change name of workflow

### ISSUE THREAD

**Issue by solairen** [solairen/terraform#3]
**Describe the solution you'd like**
Right now, the workflow for creating documentation is called: **Create documentation**. It has to be changed to be more precise e.g **Create documentation for Linode**. Also for that workflow new options must be added:

```yml
git-commit-message: Updated Linode Usage.md file
git-push-user-email: michal.oleszek@outlook.com
git-push-user-name: Michał O
```
